Message.create(text: "One day!")
Message.create(text: "Однажды в студеную")
Message.create(text: "Зимнюю пору")
Message.create(text: "Я из лесу вышел")
Message.create(text: "Быль сильный мороз")
Message.create(text: "Гляжу поднимаеться")
Message.create(text: "Медленноь в гору")
Message.create(text: "Лошадка везущая")
Message.create(text: "Хворосту воз")
Message.create(text: "Откуда дровишки")
Message.create(text: "Ступай себе с миром")
Message.create(text: "Не разговорчив ты как я")
Message.create(text: "Погляжу!")


Message.create(text: "1 One day!")
Message.create(text: "2 Однажды в студеную")
Message.create(text: "3 Зимнюю пору")
Message.create(text: "4 Я из лесу вышел")
Message.create(text: "5 Быль сильный мороз")
Message.create(text: "6 Гляжу поднимаеться")
Message.create(text: "7 Медленноь в гору")
Message.create(text: "8 Лошадка везущая")
Message.create(text: "9 Хворосту воз")
Message.create(text: "10 Откуда дровишки")
Message.create(text: "11 Ступай себе с миром")
Message.create(text: "12 Не разговорчив ты как я")
Message.create(text: "13 Погляжу!")

Message.create(text: "14 One day!")
Message.create(text: "15 Однажды в студеную")
Message.create(text: "16 Зимнюю пору")
Message.create(text: "17 Я из лесу вышел")
Message.create(text: "18 Быль сильный мороз")
Message.create(text: "19 Гляжу поднимаеться")
Message.create(text: "20 Медленноь в гору")
Message.create(text: "21 Лошадка везущая")
Message.create(text: "22 Хворосту воз")
Message.create(text: "23 Откуда дровишки")
Message.create(text: "24 Ступай себе с миром")
Message.create(text: "25 Не разговорчив ты как я")
Message.create(text: "26 Погляжу!")
