Message.create(text: "One day!")
Message.create(text: "Однажды в студеную")
Message.create(text: "Зимнюю пору")
Message.create(text: "Я из лесу вышел")
Message.create(text: "Быль сильный мороз")
Message.create(text: "Гляжу поднимаеться")
Message.create(text: "Медленноь в гору")
Message.create(text: "Лошадка везущая")
Message.create(text: "Хворосту воз")
Message.create(text: "Откуда дровишки")
Message.create(text: "Ступай себе с миром")
Message.create(text: "Не разговорчив ты как я")
Message.create(text: "Погляжу!")
