Message.destroy_all
Message.create(text: "1 one!")
Message.create(text: "2 two")
Message.create(text: "3 three")
Message.create(text: "4 four")
Message.create(text: "5 five")
Message.create(text: "6 six")
Message.create(text: "7 seven")
Message.create(text: "8 eight")
Message.create(text: "9 nine")
Message.create(text: "10 ten")
